name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
        etcd: 
          image: "bitnami/etcd"
            #platform: linux/amd64
          env:
            ALLOW_NONE_AUTHENTICATION: yes
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ports:
            - 2379:2379
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -coverprofile=coverage.out -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
