name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


      #          image: "bitnami/etcd"
      #    platform: linux/amd64
      #    environment:
      #      - ALLOW_NONE_AUTHENTICATION=yes
      #      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      #    ports:
      #      - "2379:2379"
      #    networks:
      #      - app-net


jobs:
  build:
    runs-on: ubuntu-latest
    services:
      image: 
          etcd: 
            image: "bitnami/etcd"
              #platform: linux/amd64
            env:
              - ALLOW_NONE_AUTHENTICATION=yes
              - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
            port:
              - "2379:2379"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
